import { Metadata } from "next";
import DefaultLayout from "@/layout/DefaultLayout";
import { Inter } from "next/font/google";
import QueryClientProviderLayout from "@/layout/QueryClientProvider";
import { getSettings, tableSettings } from "@/services/otherApi";
import { dataSettingsApi } from "@/layout/ProviderSettings";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const generateMetadata = async  (): Promise<Metadata> => {
  const dataSettings: { data: dataSettingsApi } = await getSettings(tableSettings);
  const url = new URL(dataSettings?.data?.icon ?? "")
  const company_name = dataSettings?.data?.company?.company_name

  return {
    title: {
      default: "Trang chủ",
      template: `%s ${company_name ? `| ${company_name}` :""}`,
    },
    description: "Generated by create next app",
    icons: {
      icon: [{ url: url?.pathname, rel: 'icon' }, new URL(url?.pathname, url?.origin)]
    }
  };
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className} cz-shortcut-listen="true">
        <QueryClientProviderLayout>
          <DefaultLayout>{children}</DefaultLayout>
        </QueryClientProviderLayout>
      </body>
    </html>
  );
}
