import { Metadata } from "next";
import DefaultLayout from "@/layout/DefaultLayout";
import { Inter } from "next/font/google";
import QueryClientProviderLayout from "@/layout/QueryClientProvider";
import { getSettings, tableSettings } from "@/services/otherApi";
import { dataSettingsApi } from "@/layout/ProviderSettings";

import "./globals.css";
import { joinUrl } from "@/common/function";

const inter = Inter({ subsets: ["latin"] });

export const generateMetadata = async  (): Promise<Metadata> => {
  const dataSettings: { data: dataSettingsApi } = await getSettings(tableSettings);
  const company_name = dataSettings?.data?.company?.company_name
  const BASE_URL = joinUrl()

  return {
    metadataBase: new URL(BASE_URL),
    title: {
      default: `Trang chủ ${company_name ? `| ${company_name}` :""}`,
      template: `%s ${company_name ? `| ${company_name}` :""}`,
    },
    alternates: {
      canonical: BASE_URL
    },
    formatDetection: {
      email: false,
      address: false,
      telephone: false
    },
    verification: {
      google: "google",
      yandex: "yandex"
    },
    openGraph: {
      title: {
        default: `Trang chủ ${company_name ? `| ${company_name}` :""}`,
        template: `%s ${company_name ? `| ${company_name}` :""}`
      }
    },
    description: "Generated by create next app",
    icons: {
      icon: dataSettings?.data?.icon,
      shortcut: dataSettings?.data?.icon,
      apple: dataSettings?.data?.icon,
      other: {
        rel: 'icon',
        url: dataSettings?.data?.icon ?? "",
      },
    }
  };
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className} cz-shortcut-listen="true">
        <QueryClientProviderLayout>
          <DefaultLayout>{children}</DefaultLayout>
        </QueryClientProviderLayout>
      </body>
    </html>
  );
}
