import DefaultLayout from "@/layout/DefaultLayout";
import "./globals.css";
import { Inter } from "next/font/google";
import QueryClientProviderLayout from "@/layout/QueryClientProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Trang chủ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className} cz-shortcut-listen="true">
        <QueryClientProviderLayout>
          <DefaultLayout>{children}</DefaultLayout>
        </QueryClientProviderLayout>
      </body>
    </html>
  );
}
